camera:
  intrinsic_matrix:
    cx: 128.0
    cy: 128.0
    fx: 500.0
    fy: 500.0
lights:
  count: 6
  intensities:
    light_1: 1.0
    light_2: 1.0
    light_3: 1.0
    light_4: 1.0
    light_5: 1.0
    light_6: 1.0
  positions:
    light_1:
    - 0.7993052538854534
    - 0.0
    - 1.8333333333333333
    light_2:
    - -0.9754473379569712
    - -0.8935896658269156
    - 1.5
    light_3:
    - 0.14202009321035133
    - 1.618245711260627
    - 1.1666666666666665
    light_4:
    - 1.106214062295877
    - -1.442860354966623
    - 0.8333333333333334
    light_5:
    - -1.9068894647062573
    - 0.3373018965145074
    - 0.5
    light_6:
    - 1.6816409697898456
    - 1.0697223335737591
    - 0.16666666666666682
reconstruction:
  ground_truth_normal: sphere_chrome_data\images\ground_truth_normal.png
  hog_regularization:
    cells_per_block: !!python/tuple
    - 2
    - 2
    enabled: false
    lambda: 0.2
    orientations: 9
    pixels_per_cell: !!python/tuple
    - 8
    - 8
  input_images:
  - sphere_chrome_data\images\light_1.png
  - sphere_chrome_data\images\light_2.png
  - sphere_chrome_data\images\light_3.png
  - sphere_chrome_data\images\light_4.png
  - sphere_chrome_data\images\light_5.png
  - sphere_chrome_data\images\light_6.png
  mask_threshold: 0.1
  output_normal_map: sphere_chrome_data\output\normal_map.png
  shadow_threshold: 0.05
