camera:
  intrinsic_matrix:
    cx: 128.0
    cy: 128.0
    fx: 500.0
    fy: 500.0
lights:
  count: 6
  intensities:
    light_1: 1.0
    light_2: 1.0
    light_3: 1.0
    light_4: 1.0
    light_5: 1.0
    light_6: 1.0
  positions:
    light_1:
    - 1.4
    - 0.0
    - 1.4
    light_2:
    - 0.7000000000000001
    - 1.212435565298214
    - 1.4
    light_3:
    - -0.6999999999999997
    - 1.2124355652982142
    - 1.4
    light_4:
    - -1.4
    - 1.7145055188062944e-16
    - 1.4
    light_5:
    - -0.7000000000000006
    - -1.2124355652982137
    - 1.4
    light_6:
    - 0.7000000000000001
    - -1.212435565298214
    - 1.4
reconstruction:
  ground_truth_normal: web_render_sphere_black-oxidized-steel\images\ground_truth_normal.png
  hog_regularization:
    cells_per_block: !!python/tuple
    - 2
    - 2
    enabled: false
    lambda: 0.2
    orientations: 9
    pixels_per_cell: !!python/tuple
    - 8
    - 8
  input_images:
  - web_render_sphere_black-oxidized-steel\images\light_1.png
  - web_render_sphere_black-oxidized-steel\images\light_2.png
  - web_render_sphere_black-oxidized-steel\images\light_3.png
  - web_render_sphere_black-oxidized-steel\images\light_4.png
  - web_render_sphere_black-oxidized-steel\images\light_5.png
  - web_render_sphere_black-oxidized-steel\images\light_6.png
  mask_threshold: 0.1
  output_normal_map: web_render_sphere_black-oxidized-steel\output\normal_map.png
  shadow_threshold: 0.05
