camera:
  intrinsic_matrix:
    cx: 128.0
    cy: 128.0
    fx: 500.0
    fy: 500.0
lights:
  count: 4
  intensities:
    light_1: 1.0
    light_2: 1.0
    light_3: 1.0
    light_4: 1.0
  positions:
    light_1:
    - 0.9682458365518543
    - 0.0
    - 1.75
    light_2:
    - -1.1512167919200957
    - -1.0546088839001893
    - 1.25
    light_3:
    - 0.1620916318447934
    - 1.8469505415375616
    - 0.7500000000000002
    light_4:
    - 1.2073334356031016
    - -1.5747526711438882
    - 0.2500000000000002
reconstruction:
  ground_truth_normal: web_render_sphere_lowpoly_aventurnine\images\ground_truth_normal.png
  hog_regularization:
    cells_per_block: !!python/tuple
    - 2
    - 2
    enabled: false
    lambda: 0.2
    orientations: 9
    pixels_per_cell: !!python/tuple
    - 8
    - 8
  input_images:
  - web_render_sphere_lowpoly_aventurnine\images\light_1.png
  - web_render_sphere_lowpoly_aventurnine\images\light_2.png
  - web_render_sphere_lowpoly_aventurnine\images\light_3.png
  - web_render_sphere_lowpoly_aventurnine\images\light_4.png
  mask_threshold: 0.1
  output_normal_map: web_render_sphere_lowpoly_aventurnine\output\normal_map.png
  shadow_threshold: 0.05
