camera:
  intrinsic_matrix:
    cx: 128.0
    cy: 128.0
    fx: 500.0
    fy: 500.0
lights:
  count: 4
  intensities:
    light_1: 1.0
    light_2: 1.0
    light_3: 1.0
    light_4: 1.0
  positions:
    light_1:
    - 0.502518907629606
    - 0.502518907629606
    - 0.7035264706814484
    light_2:
    - -0.502518907629606
    - 0.502518907629606
    - 0.7035264706814484
    light_3:
    - 0.502518907629606
    - -0.502518907629606
    - 0.7035264706814484
    light_4:
    - -0.502518907629606
    - -0.502518907629606
    - 0.7035264706814484
reconstruction:
  ground_truth_normal: test_data\images\ground_truth_normal.png
  hog_regularization:
    cells_per_block: !!python/tuple
    - 2
    - 2
    enabled: false
    lambda: 0.2
    orientations: 9
    pixels_per_cell: !!python/tuple
    - 8
    - 8
  input_images:
  - test_data\images\light_1.jpg
  - test_data\images\light_2.jpg
  - test_data\images\light_3.jpg
  - test_data\images\light_4.jpg
  mask_threshold: 0.1
  output_normal_map: test_data\output\normal_map.png
  shadow_threshold: 0.05
